apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  namespace: monitoring
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    path: /metrics
